blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/Feberdin/tesla-ha/security/advisories/new
    about: Bitte Sicherheitslücken nur privat melden.
