"""Tesla OAuth authorize preflight checks.

Purpose:
    Checks the Tesla `/authorize` URL before Home Assistant opens the browser.
    Tesla validates the `client_id` and `redirect_uri` at that point, so this
    catches the common "redirect_uri is not registered for this client_id"
    setup error while the user is still inside the Home Assistant config flow.

Input / Output:
    Input is the exact authorize URL generated by Home Assistant. Output is a
    small result object with a Home Assistant translation key and a safe detail
    string for setup forms.

Important invariants:
    This module never receives or sends the client secret, OAuth tokens or Tesla
    account credentials. The preflight call is an unauthenticated GET to the
    same authorize endpoint the browser would open.

Debugging:
    If this check reports `oauth_preflight_redirect_uri`, compare the displayed
    Redirect URI with the Allowed Redirect URI list in the Tesla Developer
    Portal. If it reports `oauth_preflight_client_id`, compare the displayed
    Client ID with the Tesla app's Credentials & API page.
"""

from __future__ import annotations

from dataclasses import dataclass
import re

from aiohttp import ClientError


@dataclass(frozen=True)
class OAuthPreflightResult:
    """Result returned by the Tesla authorize preflight check."""

    ok: bool
    error_key: str | None = None
    detail: str = ""


_REDIRECT_ERROR_PATTERNS = (
    "redirect_uri supplied is not registered",
    "redirect_uri is not registered",
    "don't recognize this redirect_uri",
    "do not recognize this redirect_uri",
    "not recognize this redirect_uri",
    "redirect_uri found in your app details",
    "invalid redirect uri",
)

_CLIENT_ID_ERROR_PATTERNS = (
    "don't recognize this client_id",
    "do not recognize this client_id",
    "not recognize this client_id",
    "invalid client_id",
    "client_id is invalid",
    "unknown client_id",
)


async def async_check_tesla_authorize_url(
    hass,
    authorize_url: str,
) -> OAuthPreflightResult:
    """Call Tesla's authorize endpoint and classify setup errors."""

    from homeassistant.helpers.aiohttp_client import async_get_clientsession

    session = async_get_clientsession(hass)
    try:
        async with session.get(
            authorize_url,
            allow_redirects=True,
            headers={"User-Agent": "HomeAssistant-tesla_ha-oauth-preflight"},
        ) as response:
            text = await response.text(errors="replace")
    except (TimeoutError, ClientError) as err:
        return OAuthPreflightResult(
            ok=False,
            error_key="oauth_preflight_unreachable",
            detail=str(err),
        )

    detected_error = detect_authorize_error(text)
    if detected_error:
        return OAuthPreflightResult(
            ok=False,
            error_key=detected_error,
            detail=summarize_authorize_error(text),
        )

    if 400 <= response.status < 500:
        return OAuthPreflightResult(
            ok=False,
            error_key="oauth_preflight_failed",
            detail=f"HTTP {response.status}",
        )

    return OAuthPreflightResult(ok=True)


def detect_authorize_error(response_text: str) -> str | None:
    """Return a Home Assistant error key for known Tesla authorize failures."""

    normalized = _normalize_text(response_text)
    if "redirect_uri" in normalized and any(
        pattern in normalized for pattern in _REDIRECT_ERROR_PATTERNS
    ):
        return "oauth_preflight_redirect_uri"

    if "client_id" in normalized and any(
        pattern in normalized for pattern in _CLIENT_ID_ERROR_PATTERNS
    ):
        return "oauth_preflight_client_id"

    return None


def summarize_authorize_error(response_text: str) -> str:
    """Return a short, display-safe summary of Tesla's authorize error page."""

    normalized = _normalize_text(response_text)
    for marker in ("redirect_uri", "client_id"):
        index = normalized.find(marker)
        if index == -1:
            continue

        start = max(index - 80, 0)
        end = min(index + 180, len(normalized))
        return normalized[start:end].strip()

    return normalized[:240].strip()


def _normalize_text(text: str) -> str:
    """Collapse markup and whitespace so Tesla error text is searchable."""

    without_markup = re.sub(r"<[^>]+>", " ", text)
    without_quotes = without_markup.replace("'", " ").replace('"', " ")
    return re.sub(r"\s+", " ", without_quotes).strip().lower()
